services:
  e2ee-chat-mysql:
    image: mysql:8.4
    container_name: e2ee-chat-mysql

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_USER: ${MYSQL_USER:-e2ee-chat-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-e2ee-chat-user-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-e2ee-chat-server-db}

    volumes:
      - e2ee-chat-server-db:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u${MYSQL_USER:-e2ee-chat-user}",
          "-p${MYSQL_PASSWORD:-e2ee-chat-user-password}"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

    restart: unless-stopped


  e2ee-chat-server:
    build:
      context: ./e2ee-chat-server
      dockerfile: Dockerfile

    container_name: e2ee-chat-server

    environment:
      DB_URL: jdbc:mysql://e2ee-chat-mysql:3306/${MYSQL_DATABASE:-e2ee-chat-server-db}
      DB_USERNAME: ${MYSQL_USER:-e2ee-chat-user}
      DB_PASSWORD: ${MYSQL_PASSWORD:-e2ee-chat-user-password}
      ALLOWED_ORIGINS: http://localhost:5173,http://127.0.0.1:5173

    ports:
      - "8080:8080"

    depends_on:
      e2ee-chat-mysql:
        condition: service_healthy

    restart: unless-stopped

  e2ee-chat-client:
    build:
      context: ./e2ee-chat-client
      dockerfile: Dockerfile

    container_name: e2ee-chat-client

    ports:
      - "5173:80"

    depends_on:
      - e2ee-chat-server

    restart: unless-stopped

volumes:
  e2ee-chat-server-db:
